### ISSUE TITLE
(make-tempo-map) triggers error

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#23]
https://github.com/mdedwards/slippery-chicken/blob/a21d7537888686ab23a181771ad24b85cd042185/tempo-map.lsp#L101

Despite passing the UT, the example triggers an error. If I isolate the code from the UT, this also triggers and error.

```lisp
(make-tempo-map 'tm '((1 44) (4 66) (7 (h 60))))

=> change-map::num-sequences: method not applicable in this class.

(make-tempo-map
             'tc
             (tempo-curve-to-map nil '(10 q (0 60 100 120)) 500))

=> change-map::num-sequences: method not applicable in this class.
```

**Comment by mdedwards** [comment]
Ooh, there's an obscure one! Thanks for this. Only happens when you want to print the object, not when you call the function to instantiate one. I think I was a little rigorous when issuing an error if num-sequences was called on a change-map so I've change this to return NIL instead. Now works for me. I've pulled your latest source, merged, checked-in my change and run all tests.

**Comment by danieljamesross** [comment]
I know how to find them!
