### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by timpauli** [mdedwards/slippery-chicken#30]
Hi,

every time I load `all.lsp` I get 3 warnings:

````
WARNING: 
redefining FLATS-TO-SHARPS (#<STANDARD-CLASS SLIPPERY-CHICKEN::CHORD>) in DEFMETHOD
"/home/inkeye/Desktop/3kompositionbachelor/partitursynthese/sc/src/event.lsp"
````

````
; file: /home/user/sc/src/wolfram.lsp
; in: DEFMETHOD VERIFY-AND-STORE :AFTER (WOLFRAM)
;     (SLIPPERY-CHICKEN::STATE-CHECK
;      (SLIPPERY-CHICKEN::INITIAL-STATE SLIPPERY-CHICKEN::W))
; 
; caught STYLE-WARNING:
;   undefined function: SLIPPERY-CHICKEN::STATE-CHECK
; 
; compilation unit finished
;   Undefined function:
;     STATE-CHECK
;   caught 1 STYLE-WARNING condition

; file: /home/user/sc/src/wolfram.lsp
; in: DEFMETHOD GENERATE (WOLFRAM T)
;     (SLIPPERY-CHICKEN::STATE-CHECK SLIPPERY-CHICKEN::START)
; 
; caught STYLE-WARNING:
;   undefined function: SLIPPERY-CHICKEN::STATE-CHECK
; 
; compilation unit finished
;   Undefined function:
;     STATE-CHECK
;   caught 1 STYLE-WARNING condition
````

Is this intended?

Thanks a lot
Best
Tim

**Comment by mdedwards** [comment]
looks like @Dan added FLATS-TO-SHARPS to the event class and there are a couple of problems with this. 

1. forgot to change the class from chord to event?
2. there's code duplication in this and sharps-to-flats: instead of doing that loop that the chord class does, the event method should simply call the chord method

**Comment by danieljamesross** [comment]
Oh yes, well spotted. 

Fixing now and writing test too...

**Comment by mdedwards** [comment]
those wolfram warnings can be ignored: I'm surprised you only get three warnings Tim as I get loads. I once spent a while trying to stop these from being issued but all the code that's supposed to suppress them failed miserably.

in any case, the state-check warning arises simply because it's defined after it's called. there are no forward declarations in lisp but they also shouldn't be necessary. sbcl is simply whining. other lisps don't bother you.

cheers, michael

**Comment by danieljamesross** [comment]
> sbcl is simply whining.

The hardcore sbcl crew would refute this in a very long and angry email thread

**Comment by mdedwards** [comment]
let them do so and I'll point out that all their examples of how to turn off warnings simply don't work

**Comment by danieljamesross** [comment]
My issues should be fixed now, plz git pull

**Comment by mdedwards** [comment]
without wishing to be pedantic, there's no need to have an if in the event method: instead define just one method for pitch and chord alike and then:

```
(defmethod flats-to-sharps ((e event) &optional clone written)
  (let ((event (if clone (clone e) e)))
    (flats-to-sharps (if written
			 (written-pitch-or-chord event)
			 (pitch-or-chord event)))
    event))
```

I would make cloning optional (and by default off) so that you can do this on a bunch of events with out having to collect or otherwise replace existing events.

I'd also allow this to be done to the written or sounding pitches.

**Comment by danieljamesross** [comment]
Hmmm. perhaps we don't need the clone then?

**Comment by mdedwards** [comment]
i would say we do: nice feature, but default to nil

**Comment by danieljamesross** [comment]
OK, getting to this now.

I'd need to add some setf-ing to the code above, no?

**Comment by mdedwards** [comment]
if you can prefer i can do it and then you can take a look and see what i mean

**Comment by danieljamesross** [comment]
I think I almost have it, but it's not quite right. I removed the plurals for the s'es so that the methods all match but the event method doesn't work properly.

```lisp
(defmethod flat-to-sharp ((p pitch) &optional clone written)
  (declare (ignore clone written))
  (if (flat p)
      (setf p (enharmonic p))
      p))

(defmethod flat-to-sharp ((c chord) &optional clone written)
  (declare (ignore clone written))
  (let ((c-list '()))
    (loop for cc in (data c) do
	 (push (flat-to-sharp cc) c-list))
    (setf c (make-chord (reverse c-list)))
    c))

(defmethod flat-to-sharp ((e event) &optional clone written)
  (let ((event (if clone (clone e) e)))
    (flat-to-sharp (if written
		       (written-pitch-or-chord event)
		       (pitch-or-chord event)))
    event))

```

**Comment by mdedwards** [comment]
not sure what you mean. what doesn't work? need failing code. or is it just that you need a setf:
```

(defmethod flat-to-sharp ((e event) &optional clone written)
  (let* ((event (if clone (clone e) e))
         (slot (if written
                   'written-pitch-or-chord
                   'pitch-or-chord))
         (poc (slot-value event slot))
         (fts (flat-to-sharp poc)))
    (setf (slot-value event slot) fts)
    event))
```

**Comment by danieljamesross** [comment]
Yes, that makes more sense. None of the tests were passing because the event method wasn't actually returning the setf'd event. I'll update and run tests.
