### ISSUE TITLE
sc ascii art

### ISSUE THREAD

**Issue by danieljamesross** [mdedwards/slippery-chicken#40]
The ascii art printed when sc is loaded does not match the main logo. Can we replace with something else fancier?

If you use the following code to load the attached file you get something rather swiz.

```lisp
(let ((in (open "~/slippery-chicken_hi-res-no_background.ansi.txt")))
  (when in
    (loop for line = (read-line in nil)
         while line do (format t "~a~%" line))
    (close in)))
```
[slippery-chicken_hi-res-no_background.ansi.txt](https://github.com/mdedwards/slippery-chicken/files/4793663/slippery-chicken_hi-res-no_background.ansi.txt)

**Comment by danieljamesross** [comment]
You get a nice(ish) chicken when you load sc now

**Comment by mdedwards** [comment]
Indeed thanks. I've still got a soft spot for my old chicken though :/ I'll leave yours however. Best, Michael

July 6, 2020 4:18:00 PM CEST danieljamesross <notifications@github.com> wrote:

You get a nice(ish) chicken when you load sc now
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/mdedwards/slippery-chicken/issues/40#issuecomment-654267225","url": "https://github.com/mdedwards/slippery-chicken/issues/40#issuecomment-654267225","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

______________________________
 
michael edwards
 
m@michael-edwards.org
http://www.michael-edwards.org
PGP Public Key:
http://michael-edwards.org/pgp.txt
______________________________

----
From: m@michael-edwards.org
To: reply@reply.github.com
Jul 6, 2020, 5:02:31 PM

**Comment by danieljamesross** [comment]
The old chicken will load if you remove sc-ascii-chicken.txt. Could add a second optional arg if you like? 

`(defun sc &optional (logo t) (sc-legacy-chicken nil)` ?

**Comment by mdedwards** [comment]
too sweet! nah, it's ok, i can delete/rename that file if i'm feeling the need :)

July 6, 2020 5:29:17 PM CEST danieljamesross <notifications@github.com> wrote:

The old chicken will load if you remove sc-ascii-chicken.txt. Could add a second optional arg if you like?
(defun sc &optional (logo t) (sc-legacy-chicken nil) ?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/mdedwards/slippery-chicken/issues/40#issuecomment-654307704","url": "https://github.com/mdedwards/slippery-chicken/issues/40#issuecomment-654307704","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

______________________________
 
michael edwards
 
m@michael-edwards.org
http://www.michael-edwards.org
PGP Public Key:
http://michael-edwards.org/pgp.txt
______________________________

----
From: m@michael-edwards.org
To: reply@reply.github.com
Jul 6, 2020, 5:31:02 PM
