### ISSUE TITLE
Windoof and directory-namestring

### ISSUE THREAD

**Issue by Leon-Focker** [mdedwards/slippery-chicken#89]
As mentioned [here](https://github.com/mdedwards/slippery-chicken/issues/81#issuecomment-2002084569), directory-namestring on Windows does what no one would want it to do: it gets rid of the device name. Thus, if not on the standard device (c:\), the pathnames that are returned are wrong. This is very annoying, since I know of no real alternative to directory-namestring. 

The only option I see would be to write a new function like this:
```
(defun agnostic-directory-pathname (namestring)
  (make-pathname :directory  (pathname-directory namestring)
                 :device (pathname-device namestring)))
```

Then replacing all instances of directory-namestring with this new function might already help (?)

**Comment by Leon-Focker** [comment]
(BTW, this is part of the reason why clm and cmn will not work on Windows (I think).)

**Comment by mdedwards** [comment]
Interesting. If we can easily get clm working on windows (assuming a c compiler and no major issues) that would be great. Back in the day it only worked on windows for me with the very expensive Allegro Lisp.

Anyway, feel free to go agnostic as you detail above and replace all calls to directory-namestring. There shouldn't be too many. Let us know if that solves the problems on windows :)

**Comment by Leon-Focker** [comment]
Alright, I will go at the slippery chicken parts in a bit. CLM will be more complicated though, I fear that there is more than one problematic function...

**Comment by mdedwards** [comment]
Sounds good, Leon. Remember that it’s really not our responsibility to get CLM working on anyone’s system so for me that’s really low priority. Of course it would be nice if it worked on windows but the other things like Directory name String are more important for sure, as is, the FF probe stuff. You might want to try running CLM on windows in just Lisp mode, so that you don’t have the problem of integrating a C compiler.  all the best, Michael. On 17. Mar 2024, at 15:10, Leon Focker ***@***.***> wrote:﻿
Alright, I will go at the slippery chicken parts in a bit. CLM will be more complicated though, I fear that there is more than one problematic function...

**Comment by Leon-Focker** [comment]
Yes I agree. Although it would be nice if it was easy, I don't believe that it will be.

**Comment by Leon-Focker** [comment]
[This](https://github.com/mdedwards/slippery-chicken/commit/565affb414d6766138f26fac5be87610e6ff285c) should have fixed things.

**Comment by Leon-Focker** [comment]
I'm going to close this, as the issue is completed for SC.
