### ISSUE TITLE
Write install.md

### ISSUE THREAD

**Issue by rubenphilipp** [mdedwards/slippery-chicken#97]
Hi Ruben, as you've done most of the heavy lifting with asd, and as you're thus better informed as to what is necessary right now, would you be willing to go the extra mile and write install.md?

Right now my init file looks like this:

```
(require :asdf)
(load "~/ic/quicklisp/setup.lisp")
(ql:quickload 'cm)
(load "~/lisp/cmn/cmn-all.lisp")
(load "~/ic/code/lisp/clm-init.lsp")
;;; I use a symbolic link to put my repo (wherever it is) into ~/common-lisp
(asdf:load-system :slippery-chicken)
```

_Originally posted by @mdedwards in https://github.com/mdedwards/slippery-chicken/issues/90#issuecomment-2012147496_

**Comment by rubenphilipp** [comment]
Here is my first draft. Please read and correct, @mdedwards, @Leon-Focker (esp. concerning the c-compiler, windoof seciont).

Cheers
Ruben

**Comment by mdedwards** [comment]
Thanks muchly Ruben. That's a lot of Info. A few points:

- Given my experience at least, I do wonder if we can recommend asdf for CM when quick lisp would download pprce and Alexandria automatically, as far as I know
  - so assuming as you've written elsewhere that ql looks in ~/common-lisp, perhaps we should recommend for the .sbclrc a ql:quickload for sc alone as that would download missing online libs?
  -  we'd have to insist that cm and sc are downloaded/cloned by hand, along with other optional packages, in ~/common-lisp, right?
- at the very top of the .md I'd display the ql/asdf calls necessary for the expert user
  - in other words split the doc into 'for asdf/quicklisp aficionados' ,'minimum install for beginners', 'maximum install in detail'

One of the main points of moving to asdf, for me at least, was to make things as simple as possible. So links to extensive and complex git documentation when mentioning clone are a lot less helpful than pointing people to 1) the download link at the top of the GitHub repo or 2) giving them the terminal command.

Let's agree on all this before I start correcting English: it's generally excellent but there are couple of things I'd change E.g. exemplary almost always implies a very positive value judgement rather than meaning 'serving as an example'

**Comment by mdedwards** [comment]
PS we need to mention that .sbclrc is the default init file for sbcl and that it's ccl-init.lisp or .ccl-init.lisp with clozure

**Comment by Leon-Focker** [comment]
Great work!

I would modify the last sentence in the ffprobe section to include windows like this:

_"You can, of course, use apt on Linux, brew on MacOS or choco on Windows."_

Also, knowing myself and how others read such instructions, I would prefer the easy way of installation first. Else hasty readers might look at the ffprobe website and struggle for a bit before reading the next sentence. So what about:

_"In order to install ffprobe you can use apt on Linux, brew on MacOS or choco on Windows. If none of these optionas are viable for you, head to this site and install ffprobe according to the directions given there: https://ffmpeg.org/download.html."_

Then for CLM I would add:

_"Sadly getting CLM to run on Windows is kind of a struggle, if not currently impossible, because of the way Pathnames work on Windows. Thus we cannot recommend a way of installation and Windows users might have to rely on ffprobe for now."_

... or something along those lines...

Should I commit these changes to the file?

**Comment by mdedwards** [comment]
> "Sadly getting CLM to run on Windows is kind of a struggle, if not currently impossible, because of the way Pathnames work on Windows. Thus we cannot recommend a way of installation and Windows users might have to rely on ffprobe for now."

My view is still that with asdf we leave it to the user to install whatever packages they want. There are some old comments in the clm readme that point to my solution from yonks ago. The pathname problem wasn't an unassailable issue for me back then. If necessary then I'd word it like this"

CLM was not designed to run on Windows though Michael Edwards had success a long time ago on Windows 95/XP. See README.clm in the CLM distribution.

**Comment by rubenphilipp** [comment]
Thanks a lot for the detailed feedback and apologies for the delay on my side.
I'm now working on correcting and improving the document and will push a new draft today.

> in other words split the doc into 'for asdf/quicklisp aficionados' ,'minimum install for beginners', 'maximum install in detail'
https://github.com/mdedwards/slippery-chicken/issues/97#issuecomment-2017822667

This is a very good idea. I will change the structure of the document in these three sections, where the first section will contain rather technical instructions on installing slippery-chicken and the dependencies for those who have sufficient experience with CL, ASDF etc. This will refer to the complete install, while highlighting those components which are not mandatory. The second and third section will contain more detailed instructions for people with less experience or interested persons. I will use most material from the original draft, but try to make things more straightforward. I think, I will base the third section (the complete installation) on the second (minimal installation), following a short notice on the differences (here, I will draw from the introduction to the "Dependencies" section). 

> we'd have to insist that cm and sc are downloaded/cloned by hand, along with other optional packages, in ~/common-lisp, right?

Yes, at least this applies to those which are not available on Quicklisp (when the user wants to use ql). I'll try to make this more clear in section 2 and 3. 

> so assuming as you've written elsewhere that ql looks in ~/common-lisp, perhaps we should recommend for the .sbclrc a ql:quickload for sc alone as that would download missing online libs?

This could be a good idea. I will place a comment to this at some point.

> pointing people to 1) the download link at the top of the GitHub repo or 2) giving them the terminal command

That's true.

> "In order to install ffprobe you can use apt on Linux, brew on MacOS or choco on Windows. If none of these optionas are viable for you, head to this site and install ffprobe according to the directions given there: https://ffmpeg.org/download.html."

That's very good. Can you, @Leon-Focker, give an example prompt for choco which I can use in the examples? I also referred to choco in the LilyPond section, assuming LilyPond install works this way on Windows.

> CLM was not designed to run on Windows though Michael Edwards had success a long time ago on Windows 95/XP. See README.clm in the CLM distribution.

I will use this one for now.

**Comment by Leon-Focker** [comment]
To install ffprobe with choco this should suffice: `choco install ffmpeg`
And yes, `choco install lilypond` does also work

**Comment by rubenphilipp** [comment]
> To install ffprobe with choco this should suffice: `choco install ffmpeg` And yes, `choco install lilypond` does also work

That's great. Thanks!

**Comment by mdedwards** [comment]
Thanks Ruben. Just make sure that the first section is for the impatient: bare-bones init file with minimal explanatory text. The details can come below. Many people are impatient and don't want to read at all.

**Comment by rubenphilipp** [comment]
Voilà, I've just committed version 2. Please have a look. And apologies for having done multiple minor commits. I unfortunately needed to heuristically and then empirically test how GitHub Markdown handles links to headings same names as I did not find documentation on this…

**Comment by rubenphilipp** [comment]
> there are couple of things I'd change E.g. exemplary almost always implies a very positive value judgement rather than meaning 'serving as an example'

Oh, yes, Susan Sontag once (http://faculty.winthrop.edu/stockk/SELF%20PORTRAIT/Springer%20Kirchner%20sufferer.pdf) taught me that but I obviously forgot for the moment ;)

**Comment by mdedwards** [comment]
That's great Ruben, many thanks. For the very impatient and experienced ql/asdf user would it be possible to add an ultra-short section such as:

```
# in your ASDF/Quicklisp standard directory
git clone https://github.com/ormf/cm.git
git clone https://github.com/mdedwards/slippery-chicken.git

Add (ql:quickload :slippery-chicken) to your Lisp initialisation file and you're done but see below for other useful packages that most slippery chicken users will regularly use.
```

It is true, that only SC needs to be quickloaded, right? Because it will find its dependency CM in the QL folder, get PPRCE from the server, and then for CM QL will find Alexandria also online. That would be great.

**Comment by mdedwards** [comment]
Nice. I've just tarted up the top part and committed. Feel free to roll back if you don't like it.

**Comment by rubenphilipp** [comment]
That's fine, thanks! I guess we can start fine tuning the document now, right?

**Comment by mdedwards** [comment]
I think so too. Shall I go first or do you want to look again?

**Comment by rubenphilipp** [comment]
I've just read my text again and did some minor corrections (please pull). I think, now you can go over the text. It is quite likely that I have missed some things…

**Comment by mdedwards** [comment]
Excellent work Ruben. I've done a full edit. Take a look.

Are we actually ready to merge quicklisp with master and tell the world?????

**Comment by rubenphilipp** [comment]
Great. I have read through your corrections and am very happy. Thanks for finding a more elegant way to instruct the future user on how to alter global variables. 

> Are we actually ready to merge quicklisp with master and tell the world?????

Uh, that's a big question. I think so. I am testing sc very frequently on the quicklisp branch and also tried various installation methods over the course of our work.

**Comment by rubenphilipp** [comment]
Great!
